# This sets up a live NAV development environment in Docker containers.
#
# Defaults NAV to a container with Python 3.
#
version: '2'

# x-forwarder:
#   &forwarder
#   build:
#     context: tools/forward
#     args:
#       - USER
#   volumes:
#     - /run/user/1000/keyring/ssh:/auth_sock
#     - /etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts
#   environment:
#     - SSH_AUTH_SOCK=/auth_sock

services:
  nav:
    build: .
    environment:
      - NONAVSTART=0  # Set to 1 to disable startup of NAV backend processes when container starts
      - PGHOST=postgres
      - PGDATABASE=nav
      - PGUSER=postgres
    volumes:
      - .:/source
    depends_on:
      - postgres

  web:
    build: .
    command: ["/source/tools/docker/web.sh"]
    ports:
      - "80:80"
    volumes_from:
      - nav
    depends_on:
      - nav

  postgres:
    image: "postgres:9.4"

  graphite:
    build: ./tools/docker/graphite
    ports:
      - "8000:8000"
    volumes:
      - ./python/nav/etc/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./python/nav/etc/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf

  # Add a service to continuously rebuild the Sphinx documentation if the doc
  # directory is modified:
  docbuild:
    build: .
    volumes_from:
      - nav
    command: /source/tools/docker/doc-watch.sh

  # mydevice.mydomain:
  #   << : *forwarder
  #   command: /snmp_forward.sh mydevice.mydomain myvk
