# This sets up a live NAV development environment in Docker containers.
#
# Defaults NAV to a container with Python 2. If you want to work with NAV in a
# Python 3 environment, add a `docker-compose.override.yml` that sets the
# dockerfile to Dockerfile3, like so:
#
# version: '2'
# services:
#   nav:
#     build:
#       dockerfile: Dockerfile3
version: '2'
services:
  nav:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/source
    depends_on:
      - postgres
  postgres:
    image: "postgres:9.4"
  graphite:
    build: ./tools/docker/graphite
    ports:
      - "8000:8000"
    volumes:
      - ./python/nav/etc/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./python/nav/etc/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf

  # Add a service to continuously rebuild the Sphinx documentation if the doc
  # directory is modified:
  docbuild:
    build: .
    volumes_from:
      - nav
    command: sudo -u nav /source/tools/docker/doc-watch.sh
