name: Check for changelog file

on: 
  pull_request: 
      # labeled/unlabeled = label is added/removed
      # synchronize = PR's head branch was updated
      types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  towncrier:
    if: ${{ github.actor != 'dependabot[bot]' && !contains(github.event.pull_request.labels.*.name, 'nonews') }}
    runs-on: ubuntu-latest
    name: Towncrier check
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install towncrier
      run: |
        sudo apt-get install -y pipx
        pipx install towncrier
    - name: Check for changelog file
      run: towncrier check --compare-with origin/master
